version: "3"

services:
    flask-app:
        build: app
        container_name: flask-app
        # command: flask run -h 0.0.0.0 -p 5000
        command: python run.py
        restart: always
        volumes:
        - ./app/:/usr/backend/
        env_file:
        - .env
        depends_on:
            - flask-app-db

    nginx:
        image: nginx:stable-alpine
        container_name: flask-app-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf
            - ./nginx/log:/var/log/nginx
        depends_on:
            - flask-app

    flask-app-db:
        image: postgres:latest
        container_name: flask-app-db
        restart: always
        env_file:
            - .env-db

    adminer:
        image: adminer
        restart: always
        container_name: adminer
        ports:
            - 8080:8080
        depends_on:
            - flask-app-db

    # flask-app-pgadmin:
    #     container_name: flask-app-pgadmin
    #     image: dpage/pgadmin4
    #     env_file:
    #         - .env-db
    #     # ports:
    #     #     - '5050:80'
    #     volumes:
    #         - ./pgadmin:/root/.pgadmin
    #     restart: unless-stopped
    #     depends_on:
    #         - flask-app-db